### ISSUE TITLE
script crashing while executing "python manage.py migrate"

### ISSUE THREAD

**Issue by gnaneshan** [galaxyproject/cloudlaunch#104]
Hi there,

I was following instructions as given in https://github.com/galaxyproject/cloudlaunch. When running "python manage.py migrate" got the following warnings and errors. Please help to fix this.

Thank you,

Gnani

WARNINGS:
baselaunch.Application.category: (fields.W340) null has no effect on ManyToManyField.
Operations to perform:
  Apply all migrations: account, admin, auth, authtoken, baselaunch, contenttypes, djcelery, djcloudbridge, kombu_transport_django, public_appliances, sessions, sites, socialaccount
Running migrations:
  Applying baselaunch.0024_refactor_to_djcloudbridge...Traceback (most recent call last):
  File "/home/ubuntu/launcher/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 63, in execute
    return self.cursor.execute(sql)
psycopg2.InternalError: cannot drop table djcloudbridge_cloud because other objects depend on it
DETAIL:  constraint djcloudbridge_aws_cloud_ptr_id_2c8ce822_fk_djcloudbr on table djcloudbridge_aws depends on table djcloudbridge_cloud
constraint djcloudbridge_azure_cloud_ptr_id_7831e6ba_fk_djcloudbr on table djcloudbridge_azure depends on table djcloudbridge_cloud
constraint djcloudbridge_gce_cloud_ptr_id_eb405446_fk_djcloudbr on table djcloudbridge_gce depends on table djcloudbridge_cloud
constraint djcloudbridge_openst_cloud_ptr_id_190a72a6_fk_djcloudbr on table djcloudbridge_openstack depends on table djcloudbridge_cloud
constraint djcloudbridge_creden_cloud_id_1ef6e0b2_fk_djcloudbr on table djcloudbridge_credentials depends on table djcloudbridge_cloud
constraint baselaunch_applicati_target_cloud_id_72c77a8f_fk_djcloudbr on table baselaunch_applicationdeployment depends on table djcloudbridge_cloud
constraint baselaunch_applicati_default_cloud_id_266feea9_fk_djcloudbr on table baselaunch_applicationversion depends on table djcloudbridge_cloud
constraint baselaunch_applicati_cloud_id_7e853c0c_fk_djcloudbr on table baselaunch_applicationversioncloudconfig depends on table djcloudbridge_cloud
constraint baselaunch_cloudimag_cloud_id_78f7e0a9_fk_djcloudbr on table baselaunch_cloudimage depends on table djcloudbridge_cloud
HINT:  Use DROP ... CASCADE to drop the dependent objects too.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/launcher/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/launcher/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/launcher/venv/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/launcher/venv/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/launcher/venv/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/home/ubuntu/launcher/venv/lib/python3.5/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/ubuntu/launcher/venv/lib/python3.5/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/ubuntu/launcher/venv/lib/python3.5/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/ubuntu/launcher/venv/lib/python3.5/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/ubuntu/launcher/venv/lib/python3.5/site-packages/django/db/migrations/operations/special.py", line 44, in database_forwards
    database_operation.database_forwards(app_label, schema_editor, from_state, to_state)
  File "/home/ubuntu/launcher/venv/lib/python3.5/site-packages/django/db/migrations/operations/special.py", line 108, in database_forwards
    self._run_sql(schema_editor, self.sql)
  File "/home/ubuntu/launcher/venv/lib/python3.5/site-packages/django/db/migrations/operations/special.py", line 133, in _run_sql
    schema_editor.execute(statement, params=None)
  File "/home/ubuntu/launcher/venv/lib/python3.5/site-packages/django/db/backends/base/schema.py", line 120, in execute
    cursor.execute(sql, params)
  File "/home/ubuntu/launcher/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/ubuntu/launcher/venv/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/ubuntu/launcher/venv/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/ubuntu/launcher/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 63, in execute
    return self.cursor.execute(sql)
django.db.utils.InternalError: cannot drop table djcloudbridge_cloud because other objects depend on it
DETAIL:  constraint djcloudbridge_aws_cloud_ptr_id_2c8ce822_fk_djcloudbr on table djcloudbridge_aws depends on table djcloudbridge_cloud
constraint djcloudbridge_azure_cloud_ptr_id_7831e6ba_fk_djcloudbr on table djcloudbridge_azure depends on table djcloudbridge_cloud
constraint djcloudbridge_gce_cloud_ptr_id_eb405446_fk_djcloudbr on table djcloudbridge_gce depends on table djcloudbridge_cloud
constraint djcloudbridge_openst_cloud_ptr_id_190a72a6_fk_djcloudbr on table djcloudbridge_openstack depends on table djcloudbridge_cloud
constraint djcloudbridge_creden_cloud_id_1ef6e0b2_fk_djcloudbr on table djcloudbridge_credentials depends on table djcloudbridge_cloud
constraint baselaunch_applicati_target_cloud_id_72c77a8f_fk_djcloudbr on table baselaunch_applicationdeployment depends on table djcloudbridge_cloud
constraint baselaunch_applicati_default_cloud_id_266feea9_fk_djcloudbr on table baselaunch_applicationversion depends on table djcloudbridge_cloud
constraint baselaunch_applicati_cloud_id_7e853c0c_fk_djcloudbr on table baselaunch_applicationversioncloudconfig depends on table djcloudbridge_cloud
constraint baselaunch_cloudimag_cloud_id_78f7e0a9_fk_djcloudbr on table baselaunch_cloudimage depends on table djcloudbridge_cloud
HINT:  Use DROP ... CASCADE to drop the dependent objects too.

**Comment by nuwang** [comment]
Sorry to hear about this - this problem occurred due to some refactoring work we did recently and only occurs on postgres. We are working on a fix at the moment. In the meantime, can you use sqlite instead? Is this a development instance or a production instance?

**Comment by nuwang** [comment]
This has been fixed in: https://github.com/galaxyproject/cloudlaunch/commit/b90798102c1c682ade6ec8da52e22f35c86d40d8

Thanks for reporting the error and let us know whether this solves the problem.

**Comment by gnaneshan** [comment]
Hi,
Your fix solved the bug. 
Thank you very much.
Cheers,
Gnani
