### ISSUE TITLE
Specify VPC (or generic equivalent) when launching cluster [Enhancement]

### ISSUE THREAD

**Issue by MatthewRalston** [galaxyproject/cloudlaunch#45]
Hello again,
I'm working under a corporate AWS account with an individual IAM user. I can't specify a default VPC and I have to run Galaxy in a particular VPC. Could VPC selection be implemented in Cloudman and/or Cloudlaunch? I see in the Cloudman Changelog that in August, support for VPC was added in some sense, but I'm not sure how to leverage this and/or specify it while using Cloudlaunch. Will this be part of the larger October Galaxy release?

**Comment by afgane** [comment]
CloudMan supports only the generic *default* VPC but, as you've discovered, choosing a specific one is not currently available. This option is something that would need to be implemented in Cloud Launch to give a choice of the VPCs and/or the ability to create one. I have not tried this, but looking at [the code](https://github.com/galaxyproject/cloudman/blob/master/cm/clouds/ec2.py), it seems CloudMan would use the VPC where its instance is running. 

I'll add the support for VPC on my todo but I can't get to it right away. In the mean time, if you want to give it a shot and issue a PR (even partial), that would certainly speed things up.

**Comment by dannon** [comment]
Unless something else has changed recently, you should be able to launch manually into a particular non-default VPC and everything should work.  Have you tried this and found it to fail?

**Comment by MatthewRalston** [comment]
@dannon it's worth noting that I'm not running a stock Cloudman AMI, but one configured from the ansible-cloudman-playbook for CentOS. I have noted that the playbook doesn't contain steps for acquiring Cloudman or Galaxy directly (to my knowledge). Running ```find . -name galaxy.ini``` from root seems to confirm this. Is there something else that I'm missing? (There are so many playbooks etc... very impressive).

Regarding manual launch of the AMI, sure the AMI launches fine but there isn't a GUI where I can monitor things, nor does Nginx seem to be running after I launched the AMI. If I manually launch the AMI, how can I get my local cloudlaunch install (from your Dockerfile) to recognize the remote instance and connect for administration? I'll give the VPC thing a try

@afgane the AMI i'm running used the ansible-cloudman-playbook and the galaxy-os role alone. Is this sufficient for Cloudman/Cloudlaunch?

**Comment by MatthewRalston** [comment]
> I have not tried this, but looking at the code, it seems CloudMan would use the VPC where its instance is running.

@afgane, do you mean that if Cloudman/Cloudlaunch is running on EC2 within a VPC, it'll use it's own VPC to initialize the Galaxy cluster?

Also, which playbooks do I need to run to get a fully functioning Galaxy cluster but without the reference sequences?

**Comment by afgane** [comment]
I somehow missed the previous comment - sorry.

The best instructions are available on the wiki: https://wiki.galaxyproject.org/CloudMan/Building and if you don't want the indices, you’ll need to do all the steps except step number 5. All the roles are bundled under the galaxy-cloudman-playbook, which is used to properly assemble them, so you'll want to run that playbook. For a higher-level explanation of the conceptual concepts (that are then translated into Ansible roles), you can also take a look at this paper: http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=7160269&tag=1

What Dannon was saying is that if you launch a cluster manually directly from the AWS dashboard, select a VPC, and supply appropriate instance user data then CloudMan will run fine within the VPC. You'll need to compose user data as follows (replacing text in caps with proper values):
```
cloud_name: 'Amazon'
bucket_default: 'cloudman-test'
access_key: A_KEY
secret_key: S_KEY
cluster_name: NAME
password: PASSWORD
```

**Comment by MatthewRalston** [comment]
@afgane, excellent I am working on adapting that larger playbook for CentOS. I'm confused about the second part though. How can I administer the cluster on the remote node with the Cloudman/cloudlaunch interface if I don't use Cloudlaunch to launch the instance?

**Comment by dannon** [comment]
@MatthewRalston Cloudman is separate from Cloudlaunch.  Cloudlaunch is only used for actually getting the instance going, and the Cloudman application takes over after that (regardless of whether the instance is launched manually or via cloudlaunch).

**Comment by MatthewRalston** [comment]
@afgane I wouldn't mind doing this, although I have little experience with the intricacies of your software so would you mind answering some questions as I try to figure it out? 

First, it seems that Cloudlaunch acquires the "dynamic" information using methods from bioblend (e.g. bioblend.cloudman.launch in [views.py](https://github.com/galaxyproject/cloudlaunch/blob/master/biocloudcentral/views.py). I was thinking that the get_placements function is a good template for the type of request that we're looking for. 
* Given an access key, secret key, and cloud type, we would like to:

  * retrieve and display a list of subnet IDs for that user/IAM role from a function in [views.py](https://github.com/galaxyproject/cloudlaunch/blob/master/biocloudcentral/views.py)
    It seems that this first step requires the addition of a "find_subnets" method in the CloudManLauncher class, similar to the "get_placements" function. 
  * pass the selected subnet ID to bioblend.cloudman.launch method in the run_instance method in [tasks.py](https://github.com/galaxyproject/cloudlaunch/blob/master/biocloudcentral/tasks.py). This is then (eventually) passed to boto's "run_instances" method of the EC2Connection class. This method cannot accept a VPC per-se, but can launch an instance into a specific subnet of a VPC. 


Since most of the additions need to occur in bioblend, I think this is the next step.

**Comment by afgane** [comment]
Your reasoning looks good to me. An additional `Select` field in [forms.py](https://github.com/galaxyproject/cloudlaunch/blob/master/biocloudcentral/forms.py#L29) will also be needed to allow the selection of the available subnets. I am happy to help with this so please feel free to ask for help or just questions if you have any.

Having said that, in one of the other threads, I mentioned we've started working on a new library called [cloudbridge](https://github.com/gvlproject/cloudbridge) where we're abstracting all of the (multi-)cloud support code. The reason I'm brining this up is because once the library is functional, we'll integrate it into Cloud Launch (& BioBlend & CloudMan) to replace the boto code. So I'm not sure on what type of a timeline you are on but it's likely that the cloud-interaction work we're talking about here will get replaced with the migration to the new library. The integration with Cloud Launch and all the UI stuff will still need to be done here but if you'd like to contribute the VPC-related stuff to the new library, it'll have a longer lifespan.

**Comment by MatthewRalston** [comment]
Hi @afgane I finally finished configuring my AMI and galaxyFS and tried launching it from cloudlaunch and was alerted that I cannot launch my AMIs with my IAM role since we do not have a default VPC for the whole account. So. I am now revisiting this issue and have forked bioblend to begin. I'll post back once I get to the Cloudlaunch stage.

**Comment by MatthewRalston** [comment]
Hmmm I've gotten to a point where things should be passing through correctly to boto. If I pass through a subnet_id to bioblend's CloudManLauncher "launch" method, which passes this to the boto's ec2_conn "run_instances" method, I receive the following error. 

```
[2015-10-23 15:08:19,826: ERROR/MainProcess] 400 Bad Request
[2015-10-23 15:08:19,826: ERROR/MainProcess] <?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterCombination</Code><Message>The parameter groupName cannot be used with the parameter subnet</Message></Error></Errors><RequestID>6468ae1d-770c-40e0-8636-d0dfc5db5e9b</RequestID></Response>
[2015-10-23 15:08:19,827: ERROR/MainProcess] Problem launching an instance: The parameter groupName cannot be used with the parameter subnet (code InvalidParameterCombination; status 400)
Traceback (most recent call last):
  File "/home/ralstonm/Projects/bioblend/bioblend/cloudman/launch.py", line 177, in launch
    placement=placement)
  File "/home/ralstonm/.pyenv/versions/cloudlaunch/lib/python2.7/site-packages/boto/ec2/connection.py", line 973, in run_instances
    verb='POST')
  File "/home/ralstonm/.pyenv/versions/cloudlaunch/lib/python2.7/site-packages/boto/connection.py", line 1208, in get_object
    raise self.ResponseError(response.status, response.reason, body)
EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterCombination</Code><Message>The parameter groupName cannot be used with the parameter subnet</Message></Error></Errors><RequestID>6468ae1d-770c-40e0-8636-d0dfc5db5e9b</RequestID></Response>
```

I assume that [this is a boto issue](https://github.com/boto/boto/issues/350) but I'm not sure how to fix this. Some people suggest ([1](http://stackoverflow.com/questions/23037291/python-boto-how-do-you-specify-a-subnet-id-and-a-security-group), [2](https://github.com/boto/boto/issues/350)) that this can be avoided by passing through a security group id, rather than a name. It might be possible to fix this as well in bioblend by retrieving the id from the boto object and passing that instead to the run_instances method's security_group_ids parameter.
