### ISSUE TITLE
Security group create/update fails (thanks boto), no error provided to user in a GUI.

### ISSUE THREAD

**Issue by MatthewRalston** [galaxyproject/cloudlaunch#47]
This error occurs after ICMP in the except block in the section concerning inter-instance communication. The POST request fails from the boto authorize statement stating that protocol is null, which is the first parameter is the classical method. However, my boto library seems to be up to date (2.38.0) I understand that this is mostly a boto failure, although this could provide the illusion to the user that a new security group was created or that an existing security group was updated when in reality, the inter-instance communication is not successfully authorized.

```python
            # Add rule that allows communication between instances in the same SG
            g_rule_exists = False  # A flag to indicate if group rule already exists
            for rule in cmsg.rules:
                for grant in rule.grants:
                    if grant.name == cmsg.name:
                        g_rule_exists = True
                        bioblend.log.debug("Group rule already exists in the SG.")
                if g_rule_exists:
                    break
           if not g_rule_exists:
                try:
                    cmsg.authorize(src_group=cmsg)
                except EC2ResponseError as e:
                    err_msg = "A problem with security group authorization: {0} " \
                              "(code {1}; status {2})" \
                              .format(e.message, e.error_code, e.status)
                    bioblend.log.exception(err_msg)
                    progress['err_msg'] = err_msg
            bioblend.log.info("Done configuring '%s' security group" % cmsg.name)
 ```

```
[2015-10-23 15:08:19,451: DEBUG/MainProcess] Security group 'CloudMan' already exists; will add authorizations next.
[2015-10-23 15:08:19,451: DEBUG/MainProcess] Rule (20:21) already exists in the SG
[2015-10-23 15:08:19,451: DEBUG/MainProcess] Rule (22:22) already exists in the SG
[2015-10-23 15:08:19,452: DEBUG/MainProcess] Rule (80:80) already exists in the SG
[2015-10-23 15:08:19,452: DEBUG/MainProcess] Rule (443:443) already exists in the SG
[2015-10-23 15:08:19,452: DEBUG/MainProcess] Rule (8800:8800) already exists in the SG
[2015-10-23 15:08:19,452: DEBUG/MainProcess] Rule (9600:9700) already exists in the SG
[2015-10-23 15:08:19,452: DEBUG/MainProcess] Rule (30000:30100) already exists in the SG
[2015-10-23 15:08:19,452: DEBUG/MainProcess] ICMP rule already exists in CloudMan SG.
[2015-10-23 15:08:19,452: DEBUG/MainProcess] Method: POST
[2015-10-23 15:08:19,452: DEBUG/MainProcess] Path: https://ec2.amazonaws.com/
[2015-10-23 15:08:19,452: DEBUG/MainProcess] Data: 
[2015-10-23 15:08:19,453: DEBUG/MainProcess] Headers: {}
[2015-10-23 15:08:19,453: DEBUG/MainProcess] Host: ec2.amazonaws.com
[2015-10-23 15:08:19,453: DEBUG/MainProcess] Port: 443
...
[2015-10-23 15:08:19,572: DEBUG/MainProcess] <?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterValue</Code><Message>Invalid value 'null' for protocol. VPC security group rules must specify protocols explicitly.</Message></Error></Errors><RequestID>f36e61be-64fe-40fc-bac5-09227f981253</RequestID></Response>
[2015-10-23 15:08:19,573: ERROR/MainProcess] 400 Bad Request
[2015-10-23 15:08:19,573: ERROR/MainProcess] <?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterValue</Code><Message>Invalid value 'null' for protocol. VPC security group rules must specify protocols explicitly.</Message></Error></Errors><RequestID>f36e61be-64fe-40fc-bac5-09227f981253</RequestID></Response>
[2015-10-23 15:08:19,574: ERROR/MainProcess] A problem with security group authorization: Invalid value 'null' for protocol. VPC security group rules must specify protocols explicitly. (code InvalidParameterValue; status 400)
Traceback (most recent call last):
  File "/home/ralstonm/Projects/bioblend/bioblend/cloudman/launch.py", line 301, in create_cm_security_group
    cmsg.authorize(src_group=cmsg)
  File "/home/ralstonm/.pyenv/versions/cloudlaunch/lib/python2.7/site-packages/boto/ec2/securitygroup.py", line 203, in authorize
    dry_run=dry_run)
  File "/home/ralstonm/.pyenv/versions/cloudlaunch/lib/python2.7/site-packages/boto/ec2/connection.py", line 3191, in authorize_security_group
    params, verb='POST')
  File "/home/ralstonm/.pyenv/versions/cloudlaunch/lib/python2.7/site-packages/boto/connection.py", line 1227, in get_status
    raise self.ResponseError(response.status, response.reason, body)
EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterValue</Code><Message>Invalid value 'null' for protocol. VPC security group rules must specify protocols explicitly.</Message></Error></Errors><RequestID>f36e61be-64fe-40fc-bac5-09227f981253</RequestID></Response>
```

Pip freeze
```
amqp==1.0.12
anyjson==0.3.3
billiard==2.7.3.31
-e git+https://github.com/MatthewRalston/bioblend.git@126ea70c3ad90ac02406b21d032d1b1d12d3858d#egg=bioblend-master
boto==2.38.0
celery==3.0.21
dj-database-url==0.2.1
Django==1.3
django-bootstrap-toolkit==2.12.0
django-celery==3.0.17
gunicorn==19.3.0
honcho==0.6.6
Jinja2==2.7
kombu==2.5.12
MarkupSafe==0.18
mock==1.0.1
nose==1.3.0
poster==0.8.1
psycopg2==2.4.2
python-dateutil==2.1
python-memcached==1.48
pytz==2013b0
PyYAML==3.10
requests==2.8.1
requests-toolbelt==0.4.0
simplejson==3.3.0
six==1.9.0
South==0.7.3
wheel==0.24.0
```

**Comment by afgane** [comment]
Trying things out, it seems the group rule will also need to have all of its properties specified. So the authorization code in BioBlend would need to be changed to: `cmsg.authorize(src_group=cmsg, ip_protocol='tcp', from_port=0, to_port=65535)`

**Comment by MatthewRalston** [comment]
Hmm the boto error has changed after changing this. 

```
[2015-10-26 10:10:34,542: DEBUG/MainProcess] <?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterCombination</Code><Message>The parameter groupName cannot be used with the parameter subnet</Message></Error></Errors><RequestID>e72077dd-f31d-4c94-b0ac-970f6c41fe56</RequestID></Response>
[2015-10-26 10:10:34,542: ERROR/MainProcess] 400 Bad Request
[2015-10-26 10:10:34,542: ERROR/MainProcess] <?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterCombination</Code><Message>The parameter groupName cannot be used with the parameter subnet</Message></Error></Errors><RequestID>e72077dd-f31d-4c94-b0ac-970f6c41fe56</RequestID></Response>
[2015-10-26 10:10:34,543: ERROR/MainProcess] Problem launching an instance: The parameter groupName cannot be used with the parameter subnet (code InvalidParameterCombination; status 400)
Traceback (most recent call last):
  File "/home/ralstonm/Projects/bioblend/bioblend/cloudman/launch.py", line 177, in launch
    placement=placement)
  File "/home/ralstonm/.pyenv/versions/cloudlaunch/lib/python2.7/site-packages/boto/ec2/connection.py", line 973, in run_instances
    verb='POST')
  File "/home/ralstonm/.pyenv/versions/cloudlaunch/lib/python2.7/site-packages/boto/connection.py", line 1208, in get_object
    raise self.ResponseError(response.status, response.reason, body)
EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterCombination</Code><Message>The parameter groupName cannot be used with the parameter subnet</Message></Error></Errors><RequestID>e72077dd-f31d-4c94-b0ac-970f6c41fe56</RequestID></Response>
```
